import Head from 'next/head';
import Image from 'next/image';
import '../styles/globals.css';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Vem, Meteoro!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
      <footer>
        <p>Engineered by</p>
        <a
          target="_blank"
          href="https://github.com/eberjoe"
          rel="noopener noreferrer"
        >
          <Image
            src="/images/me.png"
            alt="My shrugging avatar"
            height={60}
            width={60}
          />
        </a>
        <p>Powered by</p>
        <a
          target="_blank"
          href="https://api.nasa.gov/"
          rel="noopener noreferrer"
        >
          <Image
            src="/images/nasa.png"
            alt="Nasa logo"
            height={60}
            width={60}
          />
        </a>
      </footer>
    </>
  );
}

export default MyApp;
